# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_books', to='first.Users'),
        ),
    ]
